"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var vue_1 = require("vue");
require("./style.css");
var App_vue_1 = require("./App.vue");
var ant_design_vue_1 = require("ant-design-vue");
require("ant-design-vue/dist/reset.css");
var app = (0, vue_1.createApp)(App_vue_1.default);
app.use(ant_design_vue_1.default);
app.mount('#app');
